schema_version: 1

context:
  name: "libxs"
  version: "1.0.0"

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  - url: https://github.com/hfp/${{ name }}/releases/download/${{ version }}/${{ name }}-${{ version }}.tar.gz
    sha256: de26f50cb986a2f0e4f92c0eb489d40a44f7e4c5acd22751a6cfa2829dabd04d

build:
  number: 1
  script: build.sh
  skip:
    - win

requirements:
  build:
    - ${{ compiler("c") }}
    - ${{ compiler("cxx") }}
    - ${{ compiler("fortran") }}
    - cmake >=3.13
    - ninja >=1.13

tests:
  - package_contents:
      include:
        - ${{ name }}/${{ name }}.f
        - ${{ name }}/${{ name }}.h
        - ${{ name }}/${{ name }}.mod
      lib:
        - ${{ name }}

about:
  homepage: https://libxs.readthedocs.io/en/latest
  license: BSD-3-Clause
  license_file: LICENSE.md
  summary: Portable C library providing building blocks for memory operations
  description: |
    LIBXS is a portable C library providing building blocks for memory operations,
    numerics, synchronization, and more -- with a focus on performance and minimal
    dependencies. Targets x86-64, AArch64, and RISC-V; requires only a C89 compiler.
    Originally developed as part of LIBXSMM.
  documentation: https://libxs.readthedocs.io/en/latest
  repository: https://github.com/hfp/libxs

extra:
  recipe-maintainers:
    - mkrack
